### ISSUE TITLE
[Enhancement] Remove root-level CHANGELOG

### ISSUE THREAD

**Issue by mprimeaux** [opensearch-project/helm-charts#107]
**Is your feature request related to a problem? Please describe.**
This request is cleanup from a previous merge in an attempt to reduce complexity with respect to the CHANGELOG.

**Describe the solution you'd like**
We currently have separate CHANGELOGs and READMEs for both charts. 
* OpenSearch [CHANGELOG.md](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/CHANGELOG.md) 
* OpenSearch Dashboards [CHANGELOG.md](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch-dashboards/CHANGELOG.md).

We also reference these in the root [README.md](https://github.com/opensearch-project/helm-charts#change-logs). 

I think we should remove the root-level [CHANGELOG.md](https://github.com/opensearch-project/helm-charts/blob/main/CHANGELOG.md)

**Describe alternatives you've considered**
None

I'm happy to submit a PR but preferred to discuss this with the maintainers for their views.

**Comment by mprimeaux** [comment]
@TheAlgo I don't mind. I'll take care of it.

**Comment by DandyDeveloper** [comment]
@TheAlgo I missed this. Yes, it should be removed.

**Comment by peterzhuamazon** [comment]
Hi @mprimeaux not sure if there a PR already open for this?

Thanks.

**Comment by mprimeaux** [comment]
Hi Peter. I will submit this today
