### ISSUE TITLE
[dockerRegistry][opensearch-dashboards] Add common dockerRegistry

### ISSUE THREAD

**Issue by sastorsl** [opensearch-project/helm-charts#108]
**Description.**
Add option / value to set a common docker-registry URL for opensearch-dashboards.
Use-cases:

* Organizations have a proxy docker registry
* ...have setup login to handle licenses behind a proxy docker registry
* etc

See #70 for reference.

**Describe the solution you'd like**

* Add `dockerRegistry` to `values.yaml` for opensearch-dashboards
* Add `dockerRegistry` reference to `deployment.yaml`

**Describe alternatives you've considered**
It is possible now to override `images` directly in `values.yaml`, but to be consistent with the `opensearch` chart, and in preparation of eventual coming additional images in `opensearch-dashboards` this should be added here as well.

**Additional context**
See referred PR and commits.

**Comment by peterzhuamazon** [comment]
Close this for now as it seems to be resolved by #70.
Please feel free to re-open if you still have questions.

Thanks.
