### ISSUE TITLE
[Enhancement][opensearch-dashboards] Add k8s readiness probe

### ISSUE THREAD

**Issue by Sebor** [opensearch-project/helm-charts#112]
**Is your feature request related to a problem? Please describe.**
At the present time there are no any probes in this chart.  However, for example, this [section](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml#L306) in `values.yaml` is presented

**Describe the solution you'd like**
it would be nice to have a readiness probe in the chart

**Comment by sastorsl** [comment]
Duplicate of #44 ?

**Comment by Sebor** [comment]
> Duplicate of #44 ?

You are right. But the title of the old issue looks a bit strange imho.
So I've renamed this issue to be more specific

**Comment by faabsen** [comment]
Follow up: hasn't this been already fixed with #329 and #333 and is a duplicate of #117?

**Comment by TheAlgo** [comment]
Yes I think we can close this. Thanks @faabsen 

@Sebor Feel free to re-open if you have further questions.
