### ISSUE TITLE
[Enhancement][OpenSearch & OpenSearch Dashboards] Request for Helm Repo 

### ISSUE THREAD

**Issue by doge95** [opensearch-project/helm-charts#121]
**Describe the solution you'd like**
Can we have the helm repo for OpenSearch projects? So that we can install charts easily by adding the repo. 
Something like:
```
helm repo add opensearch <https://helm repo URL>
helm repo update
helm install opensearch/opensearch-dashboards 
```

**Comment by TheAlgo** [comment]
We already have one setup. You can refer [this](https://github.com/opensearch-project/helm-charts#installation)

**Comment by doge95** [comment]
> We already have one setup. You can refer [this](https://github.com/opensearch-project/helm-charts#installation)

Oh thank you!! I missed that.
