### ISSUE TITLE
[BUG] Correct copyright notices to reflect Copyright OpenSearch Contributors

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/helm-charts#133]
Coming from opensearch-project/.github#21.

The correct copyright for open-source projects in opensearch-project is "Copyright OpenSearch Contributors". Please correct any places that say otherwise, especially where it says copyright Amazon. Make sure NOTICE.txt and README match. See opensearch-project/.github#24 for an example.

**Comment by bbarani** [comment]
Fixed in https://github.com/opensearch-project/helm-charts/pull/134

**Comment by TheAlgo** [comment]
Looks like the PR is already merged. @bbarani we are good to close this I believe.

**Comment by TheAlgo** [comment]
Closing this. Feel free to reopen if issue persists.
