### ISSUE TITLE
Publish helm charts

### ISSUE THREAD

**Issue by dblock** [opensearch-project/helm-charts#14]
Coming from opensearch-project/opensearch-devops#10 and opensearch-project/opensearch-devops#4 

consider https://github.com/helm/chart-releaser-action

**Comment by TheAlgo** [comment]
@mprimeaux We have completed the migration. You should be good to contribute now. Thanks.

**Comment by peterzhuamazon** [comment]
Hi @mprimeaux is there any progress on this task to make helm charts publish?
Thanks.

**Comment by mprimeaux** [comment]
Hi @peterzhuamazon. I will issue a PR today. My apologies for the delay.

**Comment by peterzhuamazon** [comment]
> Hi @peterzhuamazon. I will issue a PR today. My apologies for the delay.

np, thanks.
