### ISSUE TITLE
[Discuss] Easy Way to Deploy in Single/Cluster Mode.

### ISSUE THREAD

**Issue by swartz-k** [opensearch-project/helm-charts#140]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support an easy way to start OpenSearch in local machine or K8S, such as docker compose、Helm Chart or something

**Describe alternatives you've considered**
Support Helm Chart and docker deploy docs

**Comment by peterzhuamazon** [comment]
Close this for now as OpenSearch helm and guidelines has been released for months.
Please feel free to re-open if you still have questions.

Thanks.
