### ISSUE TITLE
[BUG][opensearch] setting vm.max_map_count=262144  on GKE fails

### ISSUE THREAD

**Issue by bluehawk27** [opensearch-project/helm-charts#143]
**Describe the bug**
setting vm.max_map_count=262144 on gke with the security context via the helm chart currently does not work.

**To Reproduce**
1. set sysctlVmMaxMapCount: 262144
2. set sysctl.enabled: true
3. Apply helm chart
4. sysctl error on GKE

**Expected behavior**
Sysctl should set the vm.max_map_count

**Chart Name**
opensearch 

**Screenshots**

**Host/Environment (please complete the following information):**
 - Helm Version: [e.g. 3.5.4]
 - Kubernetes Version: [e.g. 1.19.x]

Do you have any additional context?
Current workaround is to run an init container to achieve the same goal:

`extraInitContainers:

name: ini-sysctl
securityContext:
runAsUser: 0
privileged: true
image: busybox:latest
command: ['sysctl', '-w','vm.max_map_count=262144']`

**Comment by DandyDeveloper** [comment]
@bluehawk27 I am going to close this as a duplicate of https://github.com/opensearch-project/helm-charts/issues/87

Theres a slow discussion surrounding this there. 

For GKE, it seems marking the initContainer as a `privileged: true` is the only workaround for this.
