### ISSUE TITLE
 [Enhancement][OpenSearch/OpenSearch Dashboards] Make 1.2 as default image for opensearch helm charts

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/helm-charts#151]
**Is your feature request related to a problem? Please describe.**
Plans for moving the default App Version of charts to use the latest OpenSearch version.

**Describe the solution you'd like**
Change [this](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/Chart.yaml#L24) to `1.2`

**Describe alternatives you've considered**
N/A

**Additional context**
It has been close to a week for the launch of OpenSearch 1.2. It will be great to switch the default version of the charts to `1.2`

**Comment by derek-diaz** [comment]
I had updated this already on my local fork of OpenSearch helm charts since I am currently in the process of getting OpenSearch running in GKE with Security and NGINX. Might as well push it to the main project haha
