### ISSUE TITLE
[BUG][opensearch] Chart not installing in PSP enabled kubernetes clusters >= 1.21.

### ISSUE THREAD

**Issue by chbmuc** [opensearch-project/helm-charts#157]
**Describe the bug**
Chart not installing in Kubernetes clusters >= 1.21 with PodSecurityPolicies enabled.

This is because the chart want's to use `apiVersion: policy/v1`. However there is no such apiVersion and there never will be. podSecurityPolicys have been deprecated, because they will be removed completely in future Kubernetes versions.

**To Reproduce**
1. Requirement: PSP enabled kubernetes cluster >= 1.21
2. `helm install opensearch --set=podSecurityPolicy.create=true --set=rbac.create=true opensearch/opensearch`
3. `Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1"`

**Expected behavior**
Chart should install with a warning about the deprecation.

**Chart Name**
opensearch

**Host/Environment (please complete the following information):**
 - Helm Version: 3.7.1
 - Kubernetes Version: 1.21.5

**Additional context**
Suggested patch:

```patch
--- a/charts/opensearch/templates/podsecuritypolicy.yaml
+++ b/charts/opensearch/templates/podsecuritypolicy.yaml
@@ -1,10 +1,6 @@
 {{- if .Values.podSecurityPolicy.create -}}
 {{- $fullName := include "opensearch.uname" . -}}
-{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
-apiVersion: policy/v1
-{{- else -}}
 apiVersion: policy/v1beta1
-{{- end }}
 kind: PodSecurityPolicy
 metadata:
   name: {{ default $fullName .Values.podSecurityPolicy.name | quote }}
```

**Comment by TheAlgo** [comment]
@chbmuc Thanks for bringing this up. Do you plan of raising PR for it?
