### ISSUE TITLE
[Enhancement][opensearch/opensearch-dashboard] switch from image/imageTag to a different (helm default) formatting of YAML keys/values

### ISSUE THREAD

**Issue by dmpe** [opensearch-project/helm-charts#160]
**Is your feature request related to a problem? Please describe.**

I would like that both helm charts, for `opensearch` and `opensearch-dashboard`, changed how they work with `image` and `imageTag` keys. 

So instead of current way of:

```
image: "opensearchproject/opensearch"
imageTag: "1.11.0"
```

I would like this to become, more helm-native, to:

```
image: 
  repository: "opensearchproject/opensearch" 
  tag: "1.12.0"
  pullPolicy: "IfNotPresent"
```

I am fully aware that there are helm charts which vary in how they approach things, however, I working with many charts (vast majority) which have the suggested format of YAML, instead of `image+imageTag`. 

The larger reason is our use of `renovate` project which does dependency updates (of docker images) and current YAML format causes us to create and maintain hard to navigate `regex`es. 

I could provide you a PR, if the project would be willing to consider it, i.e. accept a breaking change. 
What do you think?

**Comment by peterzhuamazon** [comment]
I am not afraid of breaking changes, as long as it is in good faith.
My concern is how urgent or needed is this change?
I would get more opinions on community members on this.
@smlx @mprimeaux @DandyDeveloper that are your thoughts on this?

Thanks.

**Comment by DandyDeveloper** [comment]
@peterzhuamazon I'm all for it but it is a frustrating breaking change. 

I'm not sure why we didn't use the standard convention in the first place.

**Comment by smlx** [comment]
I am in favour of this change, it is the standard helm way of doing things. It is breaking in the sense that people have to restructure their values files but not in the sense that it will make it impossible to upgrade an existing installation.

> I'm not sure why we didn't use the standard convention in the first place.

I'm guessing `helm chart create` wasn't used.

**Comment by dmpe** [comment]
Thanks everyone for quick responses. 

> urgend/needed

Not urgend, but the change would be very welcome. The opendistro helm chart had also the same structure, and with the switch to opensearch project, this is the time (being still quite young) that we could make a good and reasonble (breaking) change as well.

**Comment by mprimeaux** [comment]
Likewise, I am in favor of the change to align with the standard Helm way of structuring that specific stanza.  Granted, we **could** make the change in a backward-compatible manner in the spirit of a deprecation policy. 

Regardless, I don't perceive this breaking change as requiring a material effort for consumers.

**Comment by dmpe** [comment]
I have created a PR for my proposed changes - see #184
