### ISSUE TITLE
[Documentation][OpenSearch/OpenSearch Dashboards] Add Contribution guidelines for the repository

### ISSUE THREAD

**Issue by TheAlgo** [opensearch-project/helm-charts#169]
**Is your feature request related to a problem? Please describe.**
Add a detailed guideline for contribution so that it need not be pointed out in every PR. This will make things hassle free for maintainers and contributors

**Describe the solution you'd like**
 Make contribution [guidelines](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md) more detailed.

**Describe alternatives you've considered**
Add the check in PR to enforce the guidelines

**Comment by TheAlgo** [comment]
@peterzhuamazon @DandyDeveloper @mprimeaux What do you guys think about it?

**Comment by peterzhuamazon** [comment]
Fixed in #195
