### ISSUE TITLE
[bug][Opensearch][OCI runtime create failed: container_linux.go:370: starting container process caused: mounting "/var/lib/kubelet/pods//volume-subpaths/config/opensearch/2" to rootfs at /run/containerd/io.containerd.runtime.v1.linux/k8s.io/opensearch/rootfs/usr/share/opensearch/config/opensearch.yml caused: not a directory: unknown]Unable to deploy opensearch through helm chart 

### ISSUE THREAD

**Issue by kunal-parsewar** [opensearch-project/helm-charts#181]
**Describe the bug**
We are trying to deploy the opensearch helm chart on AKS cluster . But while deploying below errors it is throwing when i m describing the pods.

 Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/var/lib/kubelet/pods/9a2d2d61-4a24-4044-a132-f9f30e77d150/volume-subpaths/config/opensearch/2" to rootfs at "/run/containerd/io.containerd.runtime.v1.linux/k8s.io/opensearch/rootfs/usr/share/opensearch/config/opensearch.yml" caused: not a directory: unknown

i have added below in my values.yml for mounting the config.yml.

extraVolumes:
  - name: extras
    emptyDir: {}
  - name: config-dir
    emptyDir: {}
  - name: tmp-dir
    emptyDir: {}
  - name: log-dir
    emptyDir: {}
  - name: opensearchrootca
    secret:
      secretName: opensearch-myrootca
extraVolumeMounts:
  - name: extras
    mountPath: /usr/share/extras
    readOnly: true
  - name: config-dir
    mountPath: /usr/share/opensearch/config
    readOnly: false
  - name: tmp-dir
    mountPath: /tmp
    readOnly: false
  - name: log-dir
    mountPath:  /usr/share/opensearch/logs
    readOnly: false
  - name: opensearchrootca
    mountPath: /usr/share/opensearch/config/certs
    readOnly: true

I tried the things but receiving mentioned error . Am i missing something.

**Chart Name**
opensearch

**Host/Environment (please complete the following information):**
 - Helm Version:  3.7.2
 - Kubernetes Version: 1.22.2

**Additional context**

**Comment by TheAlgo** [comment]
@kunal-parsewar which version of the chart are you using, I will need that to reproduce the issue.

**Comment by peterzhuamazon** [comment]
Close this for now as it there is no response for some time.
Please feel free to re-open if you still have questions.

Thanks.
