### ISSUE TITLE
Unable to deploy a pod using security context read only file system to true

### ISSUE THREAD

**Issue by rveeranki06** [opensearch-project/helm-charts#187]
Hi Team,

Some how I am not able to deploy or install a pod with security context read only file system to true. Do you have any alternative or solution to adhere to security context in k8s

sed: couldn't open temporary file /usr/share/opensearch/config/sedJSnoBz: Read-only file system
Exception in thread "main" org.opensearch.bootstrap.BootstrapException: java.nio.file.FileSystemException: /usr/share/opensearch/config/opensearch.keystore.tmp: Read-only file system
Likely root cause: java.nio.file.FileSystemException: /usr/share/opensearch/config/opensearch.keystore.tmp: Read-only file system

**Comment by duggiralateja** [comment]
Facing the same issue while deploying into Kubernetes. struck with above error while running.

https://github.com/opensearch-project/helm-charts/issues/166

**Comment by peterzhu1992** [comment]
@rveeranki06 @duggiralateja 
https://github.com/opensearch-project/opensearch-build/pull/1130

**Comment by peterzhuamazon** [comment]
Fixed in https://github.com/opensearch-project/opensearch-build/pull/1130
