### ISSUE TITLE
Steps to resize the persistent volume

### ISSUE THREAD

**Issue by volserverRay** [opensearch-project/helm-charts#188]
Hi there,
any idea how to resize the persistent volume used by the statefulset after the chart installed?
I have tried to modify the values and run "helm upgrade", but it shows error " Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden".

**Comment by smlx** [comment]
This is a kubernetes limitation and the only way I'm aware of to do this is along the lines of https://serverfault.com/a/989665

Maybe you could instead snapshot to S3, create the new cluster with larger volumes, and then restore into it?

**Comment by volserverRay** [comment]
hi @smlx , 
understood.
yes. currently i'm doing the same as the link suggest. and it working very well.
thank you!
