### ISSUE TITLE
[BUG][opensearch] securityConfigSecret not volumeMount(ed)

### ISSUE THREAD

**Issue by cshields** [opensearch-project/helm-charts#191]
**Describe the bug**
There is an option to use a predefined Secret for securityConfig (with the individual files within) at securityConfig.config.securityConfigSecret - setting this with the name of the Secret that contains the configs adds the secret to the list of volumes in the StatefulSet as security-config-complete, but does not add it to the list of VolumeMounts.

**To Reproduce**
1. set up a secret with the securityconfig items (config.yml, internal_users.yml, etc..)
2. assign that secret to securityConfig.config.securityConfigSecret
3. secret will be added to a pod, but not mounted.

**Expected behavior**
Should be mounted at the configured path (ie /usr/share/opensearch/plugins/opensearch-security/securityconfig)

**Chart Name**
opensearch

**Host/Environment (please complete the following information):**
 - Helm Version: 3.7.2
 - Kubernetes Version: 1.21.5

**Additional context**

I think this is a quick and easy fix but I'll leave it up to someone who works with this more to show what I'm missing.

The security-config-complete volume can come from a predefined secret or from a data: {} in the values file, as implemented in the statefulset [here](https://github.com/opensearch-project/helm-charts/blob/63847ee78834063f5f79d2f575c22e6301ea6244/charts/opensearch/templates/statefulset.yaml#L143).

However, only the data: {} option is referred to in the volumeMounts for the statefulset [here](https://github.com/opensearch-project/helm-charts/blob/63847ee78834063f5f79d2f575c22e6301ea6244/charts/opensearch/templates/statefulset.yaml#L368).

```
        {{- if .Values.securityConfig.config.data  }}
        - mountPath: {{ .Values.securityConfig.path }}
          name: security-config-complete
        {{- end }}
```

Unless I'm missing something, this should just be an inclusion of the securityConfigSecret option, like:

```
        {{- if or .Values.securityConfig.config.data .Values.securityConfig.config.securityConfigSecret  }}
        - mountPath: {{ .Values.securityConfig.path }}
          name: security-config-complete
        {{- end }}
```

**Comment by peterzhuamazon** [comment]
@DandyDeveloper @TheAlgo any thoughts?

**Comment by peterzhuamazon** [comment]
Poke again @DandyDeveloper @TheAlgo

**Comment by DandyDeveloper** [comment]
@peterzhuamazon Let me have a look round, I thought this got fixed in a PR somewhere.

**Comment by phijojo** [comment]
its working for me for all secrets except `node_dn.yml` and `whitelist.yml` . I don't see any mount option for those 2 files in `templates/statefulset.yaml `
