### ISSUE TITLE
[Feature][opensearch] need to create the multi role deployment for opensearch cluster 3 master and 2 data nodes. How to create that using single values.yaml.

### ISSUE THREAD

**Issue by kunal-parsewar** [opensearch-project/helm-charts#193]
I am trying to setup the three master and two data node cluster using the official helm chart of opensearch.

How to create the multi role deployment using single values.yaml. We need to automate the process of the cluster setup hence we cannot execute two different yaml files for the data and master nodes.

How can we do that using single values.yaml file and having template files for data and master nodes.

I tried but i am getting lot of the syntax error like below.

$ helm lint
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/data_poddisruptionbudget.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 11: block sequence entries are not allowed in this context
[ERROR] templates/data_service.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 12: block sequence entries are not allowed in this context
[ERROR] templates/data_service.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 11: block sequence entries are not allowed in this context
[ERROR] templates/data_statefulset.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 5: block sequence entries are not allowed in this context
[ERROR] templates/master_poddisruptionbudget.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 11: block sequence entries are not allowed in this context
[ERROR] templates/master_service.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 12: block sequence entries are not allowed in this context
[ERROR] templates/master_service.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 11: block sequence entries are not allowed in this context
[ERROR] templates/master_statefulset.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 5: block sequence entries are not allowed in this context
[ERROR] templates/networkpolicy.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 11: block sequence entries are not allowed in this context

Error: 1 chart(s) linted, 1 chart(s) failed

data_poddisruptionbudget.yaml

{{- if ((.Values.data).maxUnavailable) }}
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: "{{ template "opensearch.uname" . }}-pdb"
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "opensearch.selectorLabels" . | nindent 6 }}
{{- end }}

It would be really helpful if somebody tried it already earlier which such a requirement. i already spent my two days on resolving the error.

**Comment by TheAlgo** [comment]
@kunal-parsewar For multi-node cluster to my knowledge this helm chart needs to be installed multiple times. Wrote a [blog](https://opensearch.org/blog/technical-posts/2021/11/setup-multinode-cluster-kubernetes/) sometime back. Not sure of this helps though.

**Comment by kunal-parsewar** [comment]
Hi @TheAlgo I looked at this blog , but we wanted to have everything in one file. This one alternative I did check.

I solved the above error anyhow , looks like , but facing below error.

$ helm lint
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/data_statefulset.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 67: could not find expected ':'
[ERROR] templates/master_statefulset.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 67: could not find expected ':'

Error: 1 chart(s) linted, 1 chart(s) failed

Let me know if y see any error in below 

![image](https://user-images.githubusercontent.com/22716114/149324403-5c4316a5-4184-49f0-bde4-43efa480b732.png)

**Comment by TheAlgo** [comment]
> Hi @TheAlgo I looked at this blog , but we wanted to have everything in one file. This one alternative I did check.
> 
> I solved the above error anyhow , looks like , but facing below error.
> 
> $ helm lint ==> Linting . [INFO] Chart.yaml: icon is recommended [ERROR] templates/data_statefulset.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 67: could not find expected ':' [ERROR] templates/master_statefulset.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 67: could not find expected ':'
> 
> Error: 1 chart(s) linted, 1 chart(s) failed
> 
> Let me know if y see any error in below
> 
> ![image](https://user-images.githubusercontent.com/22716114/149324403-5c4316a5-4184-49f0-bde4-43efa480b732.png)

Can you attach the whole file, it is a bit tough to draw conclusive evidence from the snippet?

**Comment by smlx** [comment]
I'd recommend [helmfile](https://github.com/roboll/helmfile) for this use case.

**Comment by peterzhuamazon** [comment]
Close this for now as it seems to be resolved by community.
Please feel free to re-open if you still have questions.

Thanks.

**Comment by venky2291** [comment]
Hi @kunal-parsewar , Could you please share the helmchart for this multi-node setup.?
