### ISSUE TITLE
Opensearch-1.2.3 images not able to deploy in kubernates

### ISSUE THREAD

**Issue by ganilmca** [opensearch-project/helm-charts#196]
Hi Team,

We have tried to deploy opensearch-1.2.3 image ( which was downloaded from "docker pull opensearchproject/opensearch:1.2.3 ") as a helm based deployments, we couldn't able to deploy the cluster.

We have followed the bellow process:

1.Deploy the cluster as a helm charts:
<img width="571" alt="opensearch123-deploy" src="https://user-images.githubusercontent.com/84953972/149765979-3810080d-48c6-436f-ab4d-e9c050729c88.PNG">

2.When we try to get pods list its showing pod status as completed/crashLoopBackoff.
<img width="759" alt="opensearch123-pods-list" src="https://user-images.githubusercontent.com/84953972/149766019-58070e9e-6d33-4e8a-be40-97b2158bbba1.PNG">

3. We were not able to get any logs for these pods.
<img width="668" alt="opensearch123-logs" src="https://user-images.githubusercontent.com/84953972/149766056-0be2f63a-87cf-419e-a547-9616e86ac3e0.PNG">

4.When we tried to describe the pod we did not notice any errors.
<img width="768" alt="opensearch123-describe" src="https://user-images.githubusercontent.com/84953972/149766099-5f83fcc2-6b35-4dc2-9de3-aa1378f9b2c2.PNG">

But we could able to deploy the cluster with 1.2.1 version, change only "imagetag" in values.yaml file.
Please let us know what other changes need to be done from our end.

Is there any issue with this image?

Thanks,
Anil

**Comment by peterzhuamazon** [comment]
Hi @ganilmca have you manually try to deploy a docker container to verify whether it can run on your system?
We have fairly amount of docker changes leading to 1.2.4, but 1.2.3 should have the same scripts as 1.2.1.

Thanks.

**Comment by peterzhuamazon** [comment]
Close this for now as we have re-released 1.2.4 docker image.
Please feel free to re-open if you still have questions.

Thanks.

**Comment by Aadis-repo** [comment]
I also have the same issue, i am installing opensearch using helm which i have used inside terraform. The opensearch pod keeps getting completed --> restarting --> crashloopbackoff . 
![opensearch plan](https://user-images.githubusercontent.com/43349716/156700464-3b7814f8-4d0b-496e-95b7-5998fefb2104.jpg)

I have attached my terraform plan for opensearch where some of the details are mentioned. I also have attached the describe pod for opensearch pod.

![opensearch describe](https://user-images.githubusercontent.com/43349716/156700614-40ad7dd8-a173-468d-b0f5-352562d84c20.jpg)

Thanks
Aditya

**Comment by Aadis-repo** [comment]
I also checked with docker and its working fine with docker. Only with helm it is giving this issue

**Comment by nitinjagjivan** [comment]
I have same issue. Log says-
ERROR: [1] bootstrap checks failed
[1]: **max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]**
ERROR: OpenSearch did not exit normally - check the logs at /usr/share/opensearch/logs/opensearch-cluster.log


Tried sudo sysctl -w vm.max_map_count=262144 but no luck.
