### ISSUE TITLE
[BUG][opensearch] its not possible to use a custom opensearch image

### ISSUE THREAD

**Issue by trondhindenes** [opensearch-project/helm-charts#199]
**Describe the bug**
Because of how complex opensearch is to configure, we find it easuer to build a custom image. However, the Helm chart is constructed in such a way that it's impossible to change the opensearch image without also changing the busy box image ref.

**Comment by peterzhuamazon** [comment]
@DandyDeveloper @TheAlgo any thoughts?

@trondhindenes could you describe what you want to do with the image?
Thanks.

**Comment by trondhindenes** [comment]
Hi, I tried to make this work with the built-in helm chart vars but couldn't make it works. So instead we do:
```
FROM opensearchproject/opensearch:1.2.0
COPY opensearch_config/securityconfig_config.yml /usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
COPY opensearch_config/opensearch.yml /usr/share/opensearch/config/opensearch_new.yml
COPY opensearch_config/opensearch-docker-entrypoint.sh /usr/share/opensearch/opensearch-docker-entrypoint.sh% 
```

And then in the entrypoint script we do:
```
echo "copying hacked opensearch"
cp /usr/share/opensearch/config/opensearch_new.yml /usr/share/opensearch/config/opensearch.yml

```

As far as I can remember, we want to retain opensearch's "demo" mode so that self-generated certs are used - we don't want to generate those ourself, but still inject a custom config, which among others disable ssl over http outside the cluster, since we use kubernetes' regular letsencrypt-based ssl to terminate ssl - that's not something we want opensearch itself to do.

So all in all, the helm chart either functions in a "demo mode" or requires very complex configuration, certs, etc. We wanted to do something in between, which forced us to hack the official Dockerfiles and build our own image.

**Comment by DandyDeveloper** [comment]
There should be no reason to limit people changing the image themselves. This 100% should be resolved. I'll try and assign this to me to do, I've been very hard to give time to the project this past few weeks. I will do my best.

**Comment by prudhvigodithi** [comment]
Closing this issue, @trondhindenes please feel free to re-open if required.
Thank you
