### ISSUE TITLE
[Security Config Mount on providing securityConfigSecret][OpenSearch]

### ISSUE THREAD

**Issue by JunaidChaudry** [opensearch-project/helm-charts#210]
**Describe the bug**
The security-config-complete was not mounting when an external secret was passed using `Values.securityConfig.config.securityConfigSecret`.
According to the docs, a user should be able to pass in a pre-created secret under Values.securityConfig.config.securityConfigSecret, which can be used to provide securityConfig config files. However, a bug in the statefulset.yaml was skipping the volume mount for this use case, even though the volume was being created by it.  

**To Reproduce**
1. Pass in `Values.securityConfig.config.securityConfigSecret` instead of `Values.securityConfig.config.data`, and install the chart.
2. The chart installation will fail to mount the config files under /plugins/opensearch-security

**Expected behavior**
The ` security-config-complete` volume that is created by the statefulset should be attached as a volumeMount on the default mountPath. 

**Chart Name**
helm-charts/opensearch

**PR Fix**
https://github.com/opensearch-project/helm-charts/pull/209

**Comment by peterzhuamazon** [comment]
Fixed in #209
