### ISSUE TITLE
[BUG][opensearch] trying to disable security config / docker-entrypoint incompatible with helm chart

### ISSUE THREAD

**Issue by erSitzt** [opensearch-project/helm-charts#211]
Using the current chart version 1.7.3

What is the correct way to disable the security plugin ?

If using
```
extraEnvs:
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
```
as stated in the README i get this
```
Disabling execution of install_demo_configuration.sh for OpenSearch Security Plugin
Enabling OpenSearch Security Plugin
tee: /usr/share/opensearch/config/opensearch.yml: Read-only file system
```

Which seems correct as that is a mounted ConfigMap ? Is this intended ? 

If i set DISABLE_SECURITY_PLUGIN too  it still wont work...

**Comment by peterzhuamazon** [comment]
Close this for now as we have re-released 1.2.4 to resolve this particular issue.
Please feel free to re-open if you still have questions.

Thanks.
