### ISSUE TITLE
[Enhancement][opensearch] securityConfig.config.data with subPath

### ISSUE THREAD

**Issue by theanotherwise** [opensearch-project/helm-charts#220]
**Is your feature request related to a problem? Please describe.**
Volume with config map `securityConfig.config.data` is mounted without subPaths

**Describe the solution you'd like**
https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/templates/statefulset.yaml#L369

Add subPath to mount only specified files instead of the whole volume with config map.

**Additional context**
 Sometimes I would modify only one file instead of all..

**Comment by smlx** [comment]
I think this feature was just added in this PR?
https://github.com/opensearch-project/helm-charts/pull/200

**Comment by theanotherwise** [comment]
haha, 2 days ago, perfect! thanks :D
