### ISSUE TITLE
[Enhancement][opensearch] add selector to volumeClaimTemplates

### ISSUE THREAD

**Issue by Pale-whale** [opensearch-project/helm-charts#239]
**Is your feature request related to a problem? Please describe.**
We have many statically provided PV and we'd love to be able to pin the pvc created for the os to some of our pv

**Describe the solution you'd like**
Adding a selector field in the `volumeClaimTemplates` section

**Comment by prudhvigodithi** [comment]
Hey @Pale-whale, after diving deep, I have not seen any `matchLabels` for a statefulset `volumeClaimTemplates `, its actually a feature for the PVC.

The actual way to do for statefulset is 
```
  volumeClaimTemplates:
    - metadata:
        name: db
```

Also for your requirement I dont see any direct way to do this via statefulset.

One way you can do this is:
You can work out the names of the automatically generated PersistentVolumeClaims and then create the PV in accordingly.
So then once you install the statefulset, it will create the PersistentVolumeClaims  and bound to the pre created PV.
Example the PVC name can be as
VC_TEMPLATE_NAME-STATEFULSET_NAME-REPLICA_INDEX ---> VC_TEMPLATE_NAME is the metadata.name that I have shared above.
So when you pre create the PV you can add
```
  claimRef:
    namespace: default
    name: VC_TEMPLATE_NAME-STATEFULSET_NAME-REPLICA_INDEX 
```
This was once you deploy the statefulset, it will create a PVC as VC_TEMPLATE_NAME-STATEFULSET_NAME-REPLICA_INDEX, and your pre-created PV has this claimRef.

**Comment by peternied** [comment]
@prudhvigodithi I'm not sure you meant to tag me, I do not think I can offer much help with this discussion.  Good luck!

**Comment by prudhvigodithi** [comment]
Lol sry @peternied its @Pale-whale :)

**Comment by prudhvigodithi** [comment]
Hey @Pale-whale, can we close close this issue?
Thank you

**Comment by prudhvigodithi** [comment]
closing this issue, plz feel free to re open @Pale-whale  :) 
Thank you
