### ISSUE TITLE
Opensearch Helm -- Cluster Formation Example Code ?

### ISSUE THREAD

**Issue by Firdaus1** [opensearch-project/helm-charts#243]
Hi Opensearch community, 

I can't seem to find an example helm chart for opensearch that includes cluster formation -- i.e. has examples of a data-statefuleset.yml and master-statefulset.yml along with discovery services for it. 

I know the default opendistro helm chart includes a cluster formation.  Does someone know a place where this example resides?

appreciate your help!
Firdaus

**Comment by TheAlgo** [comment]
Hi @Firdaus1 

Not sure if I understood the question correctly but here in this helm chart if you wish to install a multi node cluster each having different roles you can just change the `values.yaml` file accordingly and install it. This chart has a different structure and offers more control at a granular level.

This [blog](https://opensearch.org/blog/technical-posts/2021/11/setup-multinode-cluster-kubernetes/) might help. Let me know if this answers your question.

**Comment by KannappanSomu** [comment]
But still , the chart doesnt have below property for ISM to work according to node type (hot/warm)? 
or am i missing something ? 

```
node.attr.temp: hot
node.attr.temp: warm
```

**Comment by KannappanSomu** [comment]
These parameters should be written under config section : opensearch.yml ? like this ? 

```
config:
      opensearch.yml: |
        **node.attr.temp: hot**
        cluster.name: opensearch-cluster
```

**Comment by KannappanSomu** [comment]
Yes , it works with above custom values.

Confirmed with cat node attributes API. I think we can close this issue.

```
GET /_cat/nodeattrs

opensearch-cluster-data-0   xxxxxxxxxxxxx  temp                            hot

opensearch-cluster-data-1   xxxxxxxxxxxxx  temp                            hot
```

**Comment by Firdaus1** [comment]
@TheAlgo yes, that's what I was looking for. Thank you!

**Comment by neo502721** [comment]
> Hi @Firdaus1
> 
> Not sure if I understood the question correctly but here in this helm chart if you wish to install a multi node cluster each having different roles you can just change the `values.yaml` file accordingly and install it. This chart has a different structure and offers more control at a granular level.
> 
> This [blog](https://opensearch.org/blog/technical-posts/2021/11/setup-multinode-cluster-kubernetes/) might help. Let me know if this answers your question.

That's not work now, because the roles change to 
```
roles:
  - master
  - ingest
  - data
  - remote_cluster_client
