### ISSUE TITLE
[BUG][opensearch] initResources not set on opensearch pods

### ISSUE THREAD

**Issue by joblanc** [opensearch-project/helm-charts#248]
**Describe the bug**
When initResources are populated in values.yaml, containers in pods do not have resources set.

**To Reproduce**
1. Populate initResources in values.yaml with requests/limits memory/cpu
2. Deploy

**Expected behavior**
Deployed containers in pods have the resources limits/requests set.

**Chart Name**
opensearch

**Host/Environment (please complete the following information):**
 - Helm Version: 3.7.1
 - Kubernetes Version: 1.21.3

**Personal patch**
I applied this patch to make it work:
```
diff --git a/charts/opensearch/templates/statefulset.yaml b/charts/opensearch/templates/statefulset.yaml
index 3cd0a55..63c16bb 100644
--- a/charts/opensearch/templates/statefulset.yaml
+++ b/charts/opensearch/templates/statefulset.yaml
@@ -222,6 +222,10 @@
         volumeMounts:
           - name: "{{ template "opensearch.uname" . }}"
             mountPath: {{ .Values.opensearchHome }}/data
+        {{- with .Values.initResources }}
+        resources:
+        {{- toYaml . | nindent 10 }}
+        {{- end }}
 {{- end }}
 {{ if .Values.keystore }}
       - name: keystore
```

**Comment by peterzhuamazon** [comment]
@prudhvigodithi please take a look when you have time.
Thanks.

**Comment by prudhvigodithi** [comment]
Hey @joblanc is this about the init keystore image ?
https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/templates/statefulset.yaml#L234-L261

**Comment by prudhvigodithi** [comment]
Hey @joblanc This [PR](https://github.com/opensearch-project/helm-charts/pull/250) should fix the issue.

**Comment by joblanc** [comment]
Thanx for the quick fix ;-)
