### ISSUE TITLE
[BUG][Dashboard] Unable to install on EKS

### ISSUE THREAD

**Issue by steveellis** [opensearch-project/helm-charts#256]
**Describe the bug**
Dashboard chart container gets into a restart loop on EKS. Unable to reach dashboard login via port forwarding. Was hoping to use this chart to get dashboard access to opensearch service domain that has been created in a VPC shared by EKS.

**To Reproduce**
1. Create opensearch domain in VPC that is shared by EKS cluster 
1. Install the chart on an EKS cluster
1. Try port forwarding to the pod and make a request
1. Do `pod log <pod name>` (see output below)

**Expected behavior**
Pod should start up without a fatal error and stay running.

**Chart Name**
Dashboard

**Screenshots**
N/A

**Host/Environment**
 - Helm Version: 3.7.0
 - Kubernetes Version: 1.21

**Additional context**
Logs from the pod:

```
{"type":"log","@timestamp":"2022-04-29T21:49:20Z","tags":["info","plugins-service"],"pid":1,"message":"Plugin \"visTypeXy\" is disabled."}
{"type":"log","@timestamp":"2022-04-29T21:49:21Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"cpu.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuPath\""}
{"type":"log","@timestamp":"2022-04-29T21:49:21Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"cpuacct.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuAcctPath\""}
{"type":"log","@timestamp":"2022-04-29T21:49:22Z","tags":["fatal","root"],"pid":1,"message":"{ Error: listen EADDRNOTAVAIL: address not available 10.0.179.4:5601\n    at Server.setupListenHandle [as _listen2] (net.js:1263:19)\n    at listenInCluster (net.js:1328:12)\n    at GetAddrInfoReqWrap.doListen (net.js:1461:7)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)\n  code: 'EADDRNOTAVAIL',\n  errno: 'EADDRNOTAVAIL',\n  syscall: 'listen',\n  address: '10.0.179.4',\n  port: 5601 }"}

 FATAL  Error: listen EADDRNOTAVAIL: address not available 10.0.179.4:5601
```
This is not a crash loop backoff. The container is in the `Running` state but restarts every 5 minutes and provides the above log. Have tried in both `ClusterIp` (the default) and `LoadBalancer` for the service type.

My source code is here: https://github.com/culibraries/folio/blob/issue-169-deploy-kiwi/pulumi/folio/search.ts.

AWS [docs here](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/vpc.html) for what I'm trying to do.

Note the stack trace in the error above. From googling on the message, this is commonly caused by the node app not having the port or and the host set in the env (it needs these items to start), which in this case would be in the app's container.

**Comment by TheAlgo** [comment]
@steveellis have we checked whether the port is available and is not getting used by some other process?

**Comment by steveellis** [comment]
@TheAlgo If I grep on the port in the services I only see one entry, for the service.
```
kubectl -n <my ns> get service -o wide | grep 5601
opensearch-dashboards               ClusterIP      172.20.144.120   <none>                                                                    5601/TCP                     2d21h   app=opensearch-dashboards,release=opensearch-dashboards
```
The ip address that is in the error message on the opensearch dashboard pod changes each time the pod restarts. However that ip address does not exist in the cluster, although it is in the CIDR range. So for example the error is:
```
FATAL  Error: listen EADDRNOTAVAIL: address not available 10.0.179.4:5601
```
But if I do `k get pods -o wide | grep  10.0.179.4` nothing is found.

In my cluster's security group I have opened `5601` to the cluster's CIDR block `10.0.0.0/16`. I have also tried `0.0.0.0/0`.

**Comment by prudhvigodithi** [comment]
Hey @steveellis can you try to ping your `OPENSEARCH_HOSTS` url inside dashboard pod?

**Comment by prudhvigodithi** [comment]
Hey @steveellis were you able to install the cluster on EKS ?

**Comment by danielbichuetti** [comment]
I'm unable. kube-probe startup issue on EKS. Pod get on an infinite restart loop.

**Comment by smlx** [comment]
Could you share your `values.yaml`?
