### ISSUE TITLE
[Enhancement]OpenSearch/OpenSearch-Dashboards Helm Chart release management.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/helm-charts#259]
**Is your feature request related to a problem? Please describe.**
From [PR](https://github.com/opensearch-project/helm-charts/pull/257), support multiple release versions to the helm charts. Release action will keep pushing new chart versions from main, with recent release `appVersion` to `2.0.0-rc1` and two days later to `1.3.2`, which again changed back main branch to 1.x and same again with anticipated next release the main will be in 2.x.

**Describe the solution you'd like**

Below are some of the suggested solutions

1. The branch main will have version 2.x.x, and allow the workflow to auto create releases just like before. Create a new 1.x branch, will have version 1.x.x. The existing workflow will only publish anything on main to github-pages, add a separate workflow to create tags for 1.x but not releases (test using existing workflow with helm chart releaser, use two branches to release to gh-pages).

2. Another approach is we can maintain separate charts under `charts/` folder with name as `opensearch-1.x` and `opensearch-2.x` and add a detailed readme on how to use a specific version, with this we dont need to modify anything with the existing workflow plus would be easier with next 3.0.0 releases.

3. Have individual releases for 1.x and 2.x and so on, maintaining a branch for each major version and create a release flow for each version branch. 

4. Since 1.x soon be out of new feature releases,  which ever solution we go with (separate branch or a separate `opensearch-1.x` chart inside `charts/` folder), we should consider not pushing any new features to 1.x.x chart and new development with helm should be in 2.x.x, so all new installations should be from 2.x.x and existing users should be eventually be on 2.x.x.

Other improvements on release process

1. Add release notes and compatibility matrix along with with each release.

2. We should also consider signing of Helm charts, this is possible using gpg.

**Comment by TheAlgo** [comment]
Can [this](https://github.com/opensearch-project/helm-charts/pull/257#issuecomment-1119582103) be included as a solution alternative? 


Also 4th and 5th should be a mandatory one, we can create separate issues for them. I don't think they coincide with solution alternatives but more on the enhancement of the process.

**Comment by prudhvigodithi** [comment]
> Can [this](https://github.com/opensearch-project/helm-charts/pull/257#issuecomment-1119582103) be included as a solution alternative?
> 
> Also 4th and 5th should be a mandatory one, we can create separate issues for them. I don't think they coincide with solution alternatives but more on the enhancement of the process.

Added @TheAlgo

**Comment by smlx** [comment]
Option 2 is the better option IMO. Did you reach out to the ingress-nginx people to see if they have any advice?

**Comment by peterzhuamazon** [comment]
> Option 2 is the better option IMO. Did you reach out to the ingress-nginx people to see if they have any advice?

@smlx We have not reach out to them but we checked their repo.
They used a hack to ignore the version increment check by using `ct lint --charts`:
```
--charts strings                       Specific charts to test. Disables changed charts detection and
                                             version increment checking. May be specified multiple times
https://github.com/opensearch-project/helm-charts/blob/main/.github/workflows/lint-test.yaml#L39
```
https://github.com/kubernetes/ingress-nginx/blob/legacy/hack/verify-chart-lint.sh#L23
https://github.com/kubernetes/ingress-nginx/blob/legacy/.github/workflows/ci.yaml#L129

Effectively they are using the same method as `CT_CHECK_VERSION_INCREMENT: false` like what @prudhvigodithi described in Option 1, there folder even has the name hack on it.

Splunk-connect-to-kubenetes also uses Option 1 to achieve: https://github.com/splunk/splunk-connect-for-kubernetes/actions/runs/1909010382/workflow

I think we should try out Option 2 since that is obviously the better setup here to avoid any hacks and disable checks.

Thanks.

**Comment by TheAlgo** [comment]
+1 for Option number 2

**Comment by peterzhuamazon** [comment]
We now have 2 different branches `1.x` and `main`, releasing two different versions of charts.

Thanks @prudhvigodithi for the tests and development on this.
And also thanks @TheAlgo @smlx chiming in on the suggestions.

I have also updated the readme with this section.
https://github.com/opensearch-project/helm-charts/blob/main/README.md#version-and-branching


![image](https://user-images.githubusercontent.com/65193828/168687761-b34eada2-f34c-4838-bffb-4a39ad218a02.png)


Thanks.
