### ISSUE TITLE
[Enhancement] Artifacthub Verified Publisher badge for OpenSearch helm charts

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/helm-charts#269]
**Is your feature request related to a problem? Please describe.**
artifcat-hub helm charts for OpenSearch [opensearch](https://artifacthub.io/packages/helm/opensearch-project-helm-charts/opensearch)
[opensearch-dashboards](https://artifacthub.io/packages/helm/opensearch-project-helm-charts/opensearch-dashboards)
are currently not verified.

**Describe the solution you'd like**
Verify the artifcat-hub helm charts for OpenSearch, connect to https://github.com/opensearch-project/helm-charts, to make sure its verified and has the right access for OpenSearch org.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by prudhvigodithi** [comment]
We should be having `verified-publisher` badge to OpenSearch helm charts https://artifacthub.io/docs/topics/repositories/#verified-publisher, any thoughts on how the artifacthub OpenSearch helm charts are managed ?
@bbarani @DandyDeveloper @TheAlgo @smlx @mprimeaux @peterzhuamazon ?

**Comment by DandyDeveloper** [comment]
@TheAlgo @peterzhuamazon 

Think this is the best Q for you or someone in Amazon?

**Comment by peterzhuamazon** [comment]
@prudhvigodithi per our discussion last time seems like we are not in control of the artifact hub charts. Can we still get it verified on there?

Thanks.

**Comment by TheAlgo** [comment]
@prudhvigodithi @peterzhuamazon Do we have the control over this artifact or is it owned by someone else?

**Comment by prudhvigodithi** [comment]
Hey @peterzhuamazon we can only get once we link the [metadata](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml) file `artifacthub-repo.yml` 
@TheAlgo thats true

**Comment by prudhvigodithi** [comment]
Closing this issue as the related change has been pushed b @viceice in PR https://github.com/opensearch-project/helm-charts/pull/502#issue-2028716193. Thank you

**Comment by viceice** [comment]
what about the official badge?

**Comment by viceice** [comment]
https://artifacthub.io/docs/topics/repositories/#official-status

somebody from the org needs to open an issue 😉
