### ISSUE TITLE
[Enhancement][Opensearch/Opensearch-Dashboards] Helm Charts are missing kubernetes health probes

### ISSUE THREAD

**Issue by lieberlois** [opensearch-project/helm-charts#328]
The helm charts don't properly ship with sufficient health checks. While the `opensearch`-chart only lacks a liveness probe, the `opensearch-dashboard`-chart lacks any kind of probes. This causes several problems:
* Deployments of Opensearch Dashboards can't be awaited (since no meaningful readinessProbe is configured)
* Deployments of Opensearch Dashboards are marked as ready, even if they aren't ready to serve traffic yet
* Deployments of both charts arent restarted by Kubernetes when stuck in an error state (only if the application actually crashes)

The missing probes should be added to guarantee availability and reliability of the deployments.

**Comment by sastorsl** [comment]
Would be a valued attribution, also discussed in #44 
The current example in `values.yaml` with `lifecycle.postStart` should at the same time be replaced with a sane `startupProbe`.
