### ISSUE TITLE
[Enhancement][opensearch] Add hostPort support for http- and transport-ports

### ISSUE THREAD

**Issue by ph311o** [opensearch-project/helm-charts#335]
**Is your feature request related to a problem? Please describe.**
There is no possibility to expose hostPort for http- and transport-ports in chart.

**Describe the solution you'd like**
2 new values:
- hostHttpPort
- hostTransportPort
hostPort only exposed  in opensearch container if values set in values.yaml

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by TheAlgo** [comment]
I understand the requirement but may I know why are you using this approach for exposing OpenSearch? From what I know the host IP can change when the container is restarted, two containers using the same hostPort cannot be scheduled on the same node and the usage of the hostPort is considered a privileged operation on OpenShift. Am I right on this? Would like to learn more from you.

**Comment by TheAlgo** [comment]
#336
