### ISSUE TITLE
[Enhancement][opensearch-dashboards]Provide entry point for installing external plugins

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/helm-charts#341]
**Is your feature request related to a problem? Please describe.**
Here is what I want to do: install an external plugin for Opensearch dashboard, but there is no entry/param to feed that. I figured to use post start lifecycle hooks to install plugins and was able to install plugins successfully that way, however to use the plugin, it also involves a schema change to add custom configs into the opensearch_dashboards.yml. I was not able to add additional configurations into the yaml file using the lifecycle hooks since the file was mounted as read only. 
I think there are 2 areas for improvement described below.

**Describe the solution you'd like**
1. Provide entry point to install external plugins
2. Provide entry point to allow changing permissions for config

**Describe alternatives you've considered**
The only other way to achieve that I think would work is to use a custom built image instead of using the official OSD image

**Additional context**
NA

**Comment by smlx** [comment]
Using a custom image is the documented way to do this https://opensearch.org/docs/latest/opensearch/install/docker#working-with-plugins

Installing at pod-start time seems very fragile.

**Comment by BionIT** [comment]
> Using a custom image is the documented way to do this https://opensearch.org/docs/latest/opensearch/install/docker#working-with-plugins
> 
> Installing at pod-start time seems very fragile.

Yeah, installing using the post start hook is the hack that is only available option without creating a custom image.
OSD has script to install plugins, and I think providing the entry to allow specifying plugins to install would be a nice feature for the community, I do find other OSD helm chart providing entries for plugins and other settings which is more flexible https://artifacthub.io/packages/helm/captnbp/opensearch-dashboards

**Comment by rishabh6788** [comment]
@peterzhuamazon @prudhvigodithi please take a look and provide your inputs.

**Comment by peterzhuamazon** [comment]
Hi @BionIT this can be an interesting feature to simplify the task.

It would be great if you can have a draft PR to showcase the possible changes.

Note that this is related to plugin installation, so it is better to add for both OpenSearch and Dashboards together.

Thanks.

**Comment by BionIT** [comment]
Sounds great! Thanks a lot @peterzhuamazon for your suggestion! Happy to work on a draft PR!

**Comment by TheAlgo** [comment]
@BionIT Are you looking for some entrypoint like this : https://github.com/opensearch-project/helm-charts/blame/aca0199c9ff1fbeb0904b1ce4bf423dc388132c2/charts/opensearch/values.yaml#L436

**Comment by BionIT** [comment]
@TheAlgo Yes, looks like OS has this, but OSD doesn't - is there a particular reason? Is it something we are interested to have for OSD plugins as well?

**Comment by TheAlgo** [comment]
Yes definitely it is good to have. Thanks for making a PR for this @BionIT

**Comment by peterzhuamazon** [comment]
Merged PR.
