### ISSUE TITLE
[BUG][opensearch] bootstrap checks failed

### ISSUE THREAD

**Issue by patsevanton** [opensearch-project/helm-charts#348]
**Describe the bug**
```
opensearch ERROR: [1] bootstrap checks failed
opensearch [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
opensearch ERROR: OpenSearch did not exit normally - check the logs at /usr/share/opensearch/logs/opensearch-cluster.log
```

**To Reproduce**
Setup k8s with 3 nodes by 2 cpu and 4 GB
```
helm repo add opensearch https://opensearch-project.github.io/helm-charts/
helm repo update
helm install opensearch opensearch/opensearch
```

**Expected behavior**
Installed opensearch

**Chart Name**
opensearch

**Screenshots**

**Host/Environment (please complete the following information):**
 - Helm Version: v3.10.1
 - Kubernetes Version: 1.21.5
 - opensearch chart version 2.6.2

How read /usr/share/opensearch/logs/opensearch-cluster.log ?
Please redirect logs to stdout.

**Comment by prudhvigodithi** [comment]
Hey @patsevanton it looks like it's an error with `max virtual memory`, can you try on nodes with larger vm.max_map_count and update here?
Thank you

**Comment by patsevanton** [comment]
@prudhvigodithi fixed by
```
werf helm install --wait opensearch opensearch/opensearch --version 2.7.0 --set sysctlInit.enabled=true
```
