### ISSUE TITLE
 [Enhancement] [filebeat] violates PodSecurity baseline:latest hostPath volumes

### ISSUE THREAD

**Issue by nitinjagjivan** [opensearch-project/helm-charts#352]
**Describe the bug**
On kubernetes v1.25 with baseline or restricted policy, the filebeat chart fails as it uses hostPath volumes 

**Chart Name**
filebeat

**Host/Environment (please complete the following information):**
 - Helm Version: [e.g. 3.7.2]
 - Kubernetes Version: [e.g. 1.25.1]

**Comment by gaiksaya** [comment]
[Triage]
Hi @nitinjagjivan ,
We just have 2 charts https://github.com/opensearch-project/helm-charts/tree/main/charts OpenSearch and OpenSearch Dashboards. Can you point us to the filebeat chart that you are trying to use?

Thanks!
