### ISSUE TITLE
How to deploy the opensearch cluster with kubernetes manifestfile

### ISSUE THREAD

**Issue by ganilmca** [opensearch-project/helm-charts#391]
Hi Team,
 I was looking for opensearch kubernates manifest file,but not able to get it from any where.
If any one has the opensearch manifest file , please share us, it will help us.

Thanks,
Anil

**Comment by prudhvigodithi** [comment]
Hey @ganilmca helm provides that out the box, please check the following sample commands
` helm install os -f ./opensearch/values.yaml ./opensearch --dry-run` ---> Outputs all the yaml files based on ur values.yaml file
`helm template --output-dir '/tmp/' 'charts/opensearch'` ---> Outputs all the yaml files in a specific directory.

Closing this issue please feel free to reopen if required.
@bbarani @rishabh6788 

Thank you
