### ISSUE TITLE
[Enhancement][opensearch] Allow user-defined labels on ingress resource

### ISSUE THREAD

**Issue by jwitko** [opensearch-project/helm-charts#394]
**Is your feature request related to a problem? Please describe.**
I am using `external-dns` with settings that makes it label-driven instead of annotation-driven. Because opensearch does not allow me to add user-defined labels to the ingress I cannot get `external-dns` to pick up the opensearch ingress and automatically create a DNS entry for the endpoint.

**Describe the solution you'd like**
I would like to be able to add user-defined labels in a similar fashion as annotations to the ingress resource created by the helm chart.

**Describe alternatives you've considered**
N/A

**Comment by prudhvigodithi** [comment]
Hey @jwitko thanks for raising an issue, I see your problem, this should be an easy fix, just like how it was added to [service labels](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml#L265-L266), we should add the same way to [ingress](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml#L369) and then you can pass the external-dns label that can added to ingress file, are you open to raise a PR?
Thank you 
@bbarani @rishabh6788

**Comment by jwitko** [comment]
@prudhvigodithi I already created the PR.  It is attached to this Issue linked above.  #390

**Comment by prudhvigodithi** [comment]
Thanks @jwitko I will take a look.
