### ISSUE TITLE
What is the right role for a coordinating node?

### ISSUE THREAD

**Issue by vmm-afonso** [opensearch-project/helm-charts#418]
Hi, This is a pretty simple and straight forward question, what should be the node.role for a coordinating node here? Because I've seen someone on the forum saying I could leave it as a remote_client_cluster and it would serve the same purpose and since setting every other role to false or setting roles: [] doesn't seem to do the job, I'm wondering if remote_client_cluster is the way to go. Ty

**Comment by smlx** [comment]
Due to https://github.com/opensearch-project/opensearch-build/issues/2129 / https://github.com/opensearch-project/OpenSearch/issues/3412 unfortunately it isn't possible to define a co-ordinating node in the chart.

I've worked around this by specifying my "coordinating" nodes with an `ingest` role.

**Comment by vmm-afonso** [comment]
Hey, thank you for the quick reply. 

Ohh ok that's unfortunate. I will give my 'coordinating' nodes the ingest role as you suggest then. 

Appreciate the help, ty!

**Comment by rishabh6788** [comment]
Seems like the query has been answered, closing the issue.
