### ISSUE TITLE
[New Chart][Data Prepper]

### ISSUE THREAD

**Issue by TheAlgo** [opensearch-project/helm-charts#45]
**Is your feature request related to a problem? Please describe.**
Chart for Data Prepper which can be used with the OpenSearch Helm Chart

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
https://opensearch.org/docs/monitoring-plugins/trace/data-prepper/

**Comment by labaq** [comment]
have any plan on this request?

**Comment by jiragrid** [comment]
Have any plan on this request for this year?

**Comment by janhoy** [comment]
This can be closed as there is a data-prepper helm chart

**Comment by LVMalekBe** [comment]
Are there plans to update the Helm charts to support new versions of Data Prepper?

**Comment by prudhvigodithi** [comment]
Hey @LVMalekBe, the Data Prepper chart is available https://artifacthub.io/packages/helm/opensearch-project-helm-charts/data-prepper, the new chart versions with upgrades will be available as the Data Prepper helm chart PR's are merged.  (example https://github.com/opensearch-project/helm-charts/blob/main/charts/data-prepper/Chart.yaml#L18). You can always update the [appVersion](https://github.com/opensearch-project/helm-charts/blob/main/charts/data-prepper/Chart.yaml#L24C1-L24C11) to the required version of the Data Prepper.
Thank you 
@dlvenable @getsaurabh02 @SergK
