### ISSUE TITLE
Missing description in opensearch chart readme

### ISSUE THREAD

**Issue by A-I-Dev** [opensearch-project/helm-charts#459]
**Describe the bug**
There is a parameter called `lifecycle:` in the values.yaml of the OpenSearch Helm chart, but there is only description for `opensearchLifecycle:` in the README.md

**To Reproduce**
1. Go to charts/opensearch/README.md
2. Search for lifecycle

**Expected behavior**
Explanation of paramater.

**Chart Name**
opensearch

**Comment by opencmit2** [comment]
@peterzhuamazon   please assign to me

**Comment by premkirank** [comment]
@prudhvigodithi can I work on this?

**Comment by prudhvigodithi** [comment]
Thanks to both @opencmit2 and @premkirank, just checking back @opencmit2 you still working on this ?

**Comment by premkirank** [comment]
@A-I-Dev what do I write in the description for lifecycle: parameter. This doesn't look like a generic parameter.
