### ISSUE TITLE
[BUG][Opensarch]  Install the repository-s3 plugin to take and restore snapshots

### ISSUE THREAD

**Issue by Ekko-liu** [opensearch-project/helm-charts#461]
**Describe the bug**
Enabled keystore and specify existed  secretname, opensearch pod failed to bring up

**To Reproduce**
1. Created opensearch.keystore file by opensearch-keystore command 
2. Created secret
```
kubectl create secret generic opkeystore --from-file=./opensearch.keystore -n test-ns
```
3. Enable keystore and specify secretName in the values.yaml
```
keystore:
  - secretName: opkeystore
```
4. Helm upgrade
5. See error

**Expected behavior**
Register the repository and take the snapshot

**Chart Name**
templates/statefulset.yaml
values.yaml

**Screenshots**
![image](https://github.com/opensearch-project/helm-charts/assets/34849381/4bd1c1bf-2268-4965-a38d-565acb3ae8eb)

**Host/Environment (please complete the following information):**
 - Helm Version: v3.11.0
 - Kubernetes Version: v1.24.6
 - Charts version: 2.8.0

**Additional context**

**Comment by Ekko-liu** [comment]
Root Cause:
Didn't specify the secretname in the volumes specification in the   templates/statefulset.yaml

Solution:

update the  templates/statefulset.yaml to add secretName
Fixed code:

```
{{- if .Values.keystore }}
      - name: keystore
        emptyDir: {}
      {{- range .Values.keystore }}
      - name: keystore-{{ .secretName }}
        secret:
          secretName: {{ .secretName }}
      {{- end }}
{{ end }}
```
old code:

```
{{- if .Values.keystore }}
      - name: keystore
        emptyDir: {}
      {{- range .Values.keystore }}
      - name: keystore-{{ .secretName }}
        secret: {{ toYaml . | nindent 12 }}
      {{- end }}
{{ end }}
```

**Comment by zelinh** [comment]
[Triage] Could you try to follow these steps [here](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore/) and see if the issue persists?

**Comment by Ekko-liu** [comment]
Thank you so much for the update, the issue was fixed.
