### ISSUE TITLE
[BUG][Opensearch] ExtraManifests do not allow structured data

### ISSUE THREAD

**Issue by Nickmman** [opensearch-project/helm-charts#463]
**Describe the bug**
extraManifests in templates should allow structured data input, for better readability and will allow for text editors to properly check for syntax errors.

**To Reproduce**
1. Deploy a Secret via ExtraObjects
2. Have the Secret use StringData
3. StringData should be structured as a normal secret
4. Obtain error "expected string, got &value.valueUnstructured"

**Expected behavior**
Objects should be created whether they are structured or not, when added properly.

**Chart Name**
Opensearch

**Screenshots**
None available.

**Host/Environment (please complete the following information):**
 - Helm Version: v3.12.1
 - Kubernetes Version: 1.26.5

**Additional context**
Will provide proposed changes via a linked PR.

**Comment by TheAlgo** [comment]
Thanks @Nickmman for creating the PR. Much appreciated.

**Comment by Nickmman** [comment]
Ended up going a different route for this, with custom logic outside of the chart. Closing.

**Comment by pierluigilenoci** [comment]
FYI https://github.com/helm/helm/issues/12653
