### ISSUE TITLE
[BUG][Opensearch] Identical docker image discrepancy 

### ISSUE THREAD

**Issue by dgisser** [opensearch-project/helm-charts#488]
**Describe the bug**
I created a [docker image](https://hub.docker.com/layers/dgisser/opensearch-gcs/1.0.5/images/sha256-50cf838aaf8bd67e9c31fbb7f90f409f7b9815f44375994e21882e2e1f5e9061?context=repo) identical to `opensearchproject/opensearch:2.11.0`, except that when I try to run the pods, they won't start and keep backing off due to the container failing, unlike `opensearchproject/opensearch:2.11.0`, which runs fine.

**To Reproduce**
1. build dockerfile that is simply `FROM opensearchproject/opensearch:2.11.0`
2. upload it to dockerhub and run it through changing `image.repository`
3. It crashes every node

**Expected behavior**
Identical behavior between images

**Chart Name**
Opensearch

**Host/Environment (please complete the following information):**
 - Helm Version: v3.10.1
 - Kubernetes Version: 1.27.3-gke.100

**Additional context**
I don't want to think that this is an issue with this repo, but I can't think of any other explanation.

**Comment by peterzhuamazon** [comment]
Hi @dgisser could you share these two items with us to help debugging the issues?
* Your new dockerfile
* Your error logs

Thanks.

**Comment by dgisser** [comment]
For sure. The dockerfile is literally just the line `FROM opensearchproject/opensearch:2.11.0`

I unfortunately don't have any logs since the container that was loading the docker image failed on startup and didn't generate any.

**Comment by smlx** [comment]
The architecture of your image is `linux/arm64`, and I don't believe OpenSearch supports anything other than `amd64`.
