### ISSUE TITLE
How to define a ML node?

### ISSUE THREAD

**Issue by andreasMore** [opensearch-project/helm-charts#489]
Hi Team,

In version 2.4 of OpenSearch, machine learning nodes have been added. I am using OpenSearch version 2.11.0. How can I define a deployment that consists of 3 nodes that do everything except ML and one node that should be used only for ML (maybe also with GPU)? For the deplyoment I want to use helm. Unfortunately I could not find a tutorial for this. 

Thanks a lot
Andreas

**Comment by peterzhuamazon** [comment]
Hi @andreasMore could you try passing the node role here?
https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml#L16-L20

@prudhvigodithi 

Thanks.

**Comment by andreasMore** [comment]
Hi @peterzhuamazon ,
thank you for your answer. Unfortunatly its not what i was looking for, because then all nodes would also have the ml role, which is not recommended.

**Comment by prudhvigodithi** [comment]
Here is an example https://opensearch.org/blog/setup-multinode-cluster-kubernetes/.
Adding @TheAlgo

**Comment by andreasMore** [comment]
Thank you for the information. Now it works as intended.

**Comment by prudhvigodithi** [comment]
Thanks for the update @andreasMore
