### ISSUE TITLE
[Enhancement][opensearch] Allow user-defined labels on ingress resource

### ISSUE THREAD

**Issue by wigust** [opensearch-project/helm-charts#498]
**Is your feature request related to a problem? Please describe.**
The [Prometheus Operator](https://github.com/prometheus-operator) allows to create [Probes objects](https://github.com/prometheus-operator/kube-prometheus/blob/ddff48cd49b7ea6273800e2ebb62a65025608aef/docs/blackbox-exporter.md) automatically for all Ingress objects. The OpenSearch API requires authentication on / and returns 401, which triggers alerts by default (not HTTP code 200-399).

**Describe the solution you'd like**
Labels could be used in kube-prometheus-stack monitoring.coreos.com/v1 Probe objects as a selector to disable creating probe for the OpenSearch Ingress.

**Describe alternatives you've considered**
Configure Blackbox exporter for authenticated connections to OpenSearch API.

**Additional context**
Similar to #394 Ingress labels could be used for other things, e.g. [external-dns](https://github.com/kubernetes-sigs/external-dns).

Pull request adding this feature is available at https://github.com/opensearch-project/helm-charts/pull/497

**Comment by opencmit2** [comment]
Hi @wigust 
The configuration .Values.labels can also be used to add custom labels.

**Comment by wigust** [comment]
Hi @opencmit2

Apologies for the slow response.

> The configuration .Values.labels can also be used to add custom labels.

It can, but as described in the pull request - it triggers to restart all OpenSearch pods which is too costly for the case of adding a label to ingress.

**Comment by wigust** [comment]
Merged in #497

Thank you for adding this feature!
