### ISSUE TITLE
[Enhancement][Opensearch] Support OpenSearch Prometheus Exporter

### ISSUE THREAD

**Issue by DandyDeveloper** [opensearch-project/helm-charts#50]
**Is your feature request related to a problem? Please describe.**
Ported from: https://github.com/opensearch-project/opensearch-devops/issues/68

Add support for the exporter. 

**Describe the solution you'd like**
Best done by mounting an initContainer that will write the plugins. This can be a bit of a pain for persistence between containers, but I will look into using the existing PVC volume to install the plugins against. 

**Describe alternatives you've considered**
N/R 

**Additional context**
N/R

**Comment by DandyDeveloper** [comment]
I have a tenantive branch ready for this. I need a little more testing. Will be done later today.

**Comment by DandyDeveloper** [comment]
@alochym01 Need to wait for some input from the maintainer see above. 

I have this working, BUT, I don't agree that authentication is needed. If it is, then we need to rely on users setting up scrape_configs themselves. 

Waiting to see what the maintainer says

**Comment by smlx** [comment]
Does the native metrics exporter plugin have much overlap with the metrics exposed by https://github.com/prometheus-community/elasticsearch_exporter ?

**Comment by DandyDeveloper** [comment]
@smlx We'll still have the same problem, won't we? Just that people will have an easier time adding the credentials through the chart. 

I'd like to see the input from the plugin side because a more native plugin to support metrics would be better then an exporter.

Especially if it can work around the security aspects of it. 

Based on: https://github.com/aparo/opensearch-prometheus-exporter/blob/master/src/main/java/org/compuscene/metrics/prometheus/PrometheusMetricsCollector.java#L85-L95

It looks like it differs greatly.

I'm actually no opposed to using another exporter. @TheAlgo @peterzhuamazon Maybe worth getting some input? 

Do we have an official OpenSearch metrics exporter / plugin? The user in question asked for https://github.com/aparo/opensearch-prometheus-exporter but this is third party.

As an alternate approach, I can just add basic support for plugins + annotations and just leave it for the user to dictate what they do with that.

**Comment by TheAlgo** [comment]
@DandyDeveloper 
> Do we have an official OpenSearch metrics exporter / plugin? The user in question asked for https://github.com/aparo/opensearch-prometheus-exporter but this is third party.

Yes this is third part. IMO we should not go ahead with a third party plugin, rather have a plugin under the `opensearch-project` umbrella and then support it in our charts. There are 2 ways : 
1. We can develop the plugin ourselves and add the facility in the chart. 
2. Ask the third party maintainers if they are willing to move it under the umbrella.

>As an alternate approach, I can just add basic support for plugins + annotations and just leave it for the user to dictate what they do with that.
I am fine with this generic approach though.

**Comment by DandyDeveloper** [comment]
@TheAlgo Thank you. IMO there shouldn't be any reason to not bring in third party options. This is OSS after all. 

If Amazon has rules specific to this, fair enough. I'm not sure I agree there should be an expectation for someone to bring in an exporter and relicense it as such. Of course, building ourselves isn't a problem but why double the efforts and close off other options? 

I guess more input is needed from everyone though. Looking forward to hearing everyone else.

**Comment by alochym01** [comment]
Hi. @DandyDeveloper 

> As an alternate approach, I can just add basic support for plugins + annotations and just leave it for the user to dictate what they do with that.

Is there a way to work around to enable plugin when waiting the author of prometheus exporter response.

Thank you

**Comment by DandyDeveloper** [comment]
@alochym01 Added a tentative PR above. Pending approval from others.
