### ISSUE TITLE
[Enhancement][opensearch-dashboards] topologySpreadConstraints for dashboards

### ISSUE THREAD

**Issue by cpockrandt** [opensearch-project/helm-charts#505]
I was wondering whether it would be beneficial to add topologySpreadConstraints to the opensearch-dashboards Helm charts, similarly to the opensearch Helm chart (https://github.com/opensearch-project/helm-charts/issues/222):

https://github.com/opensearch-project/helm-charts/blob/5bb05318ea08b8ae83c8a83e22a368a3aa6133b1/charts/opensearch/templates/statefulset.yaml#L144-L147

E.g., to distribute the pods across multiple availability zones.

**Comment by kinoute** [comment]
Interested by this as well. I was about to create a pull request for that.

**Comment by cpockrandt** [comment]
I was just about to start a PR and saw that you already opened one! Thanks @kinoute!

**Comment by prudhvigodithi** [comment]
[Untraige]
Thanks @cpockrandt for raising the issue and thanks @kinoute for the contribution, I will take a look at the PR.

**Comment by cpockrandt** [comment]
I'm closing this issue, since it was already merged three months ago.
