### ISSUE TITLE
[Enhancement][opensearch-dashboards] Add support for memory utilization in HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by Simple-Analysis** [opensearch-project/helm-charts#529]
**Is your feature request related to a problem? Please describe.**
Our Dashboards are fairly memory intensive, so we have had to modify the HPA created by the helm chart to support autoscaling based on memory utilization. 

**Describe the solution you'd like**
This feature request would enable support for memory utilization as for HPA metrics.

**Comment by Simple-Analysis** [comment]
> [Triage] Hey @Simple-Analysis, yes can add the HPA to the dashboard https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/, we can add a `enablePodAutoscaling` option in the values and update the templates with HPA, please let us know if you are interested in contributing to this :), example https://stackoverflow.com/a/70675287.

I created a PR along with this issue.

#530

**Comment by prudhvigodithi** [comment]
Thanks @Simple-Analysis I will take a look at the PR.

**Comment by Simple-Analysis** [comment]
Closing since #530 has been merged
