### ISSUE TITLE
[BUG][opensearch] ARM support Amazon base image

### ISSUE THREAD

**Issue by mrboogiee** [opensearch-project/helm-charts#534]
**Describe the bug**
I am attempting to deploy the opensearch helm chart on a SoC using a Rockchip RK3588 CPU and I run into the following issue with the configfile statefulset (I expect the same issue on other CPUs as the RK3588 is still quite new - 2 years old):
```
Found 3 pods, using pod/opensearch-cluster-master-0
Fatal glibc error: This version of Amazon Linux requires a newer ARM64 processor
                   compliant with at least ARM architecture 8.2-a with Cryptographic
                   extensions. On EC2 this is Graviton 2 or later.
```

**To Reproduce**
```
helm install --namespace=opensearch --create-namespace opensearch opensearch/opensearch --values=values.yaml
kubectl logs -n opensearch statefulsets/opensearch-cluster-master configfile
```

**Expected behavior**
I expected Opensearch to run on my k8s environment where the base image would be more open to chipsets commonly used or desired by the community.

**Chart Name**
have been able to backtrace the issue till helm chart version 2.14.0 so far but then in the pods instead of in the statefulset

**Screenshots**
n/a

**Host/Environment (please complete the following information):**
 - Helm Version: v3.13.1
 - Kubernetes Version:  v1.29.2
 - CPU: Rockchip RK3588
 - Compute Module: TuringPi RK1

**Additional context**

**Comment by DandyDeveloper** [comment]
This won't be anything to do with the helm chart and is everything to with the image build, which are all managed through here: https://github.com/opensearch-project/OpenSearch/blob/d202d90df3991daaf3e20be325cac4b323f0ed23/distribution/docker/src/docker/Dockerfile#L4

I can't find exactly where this would have changed, but if you're desperate, I'd recommend using an older tag version of the image. There's probably a good reason for introducing this change on the base image in Opensearch, but I can't find it anywhere at the moment.
