### ISSUE TITLE
[Enhancement][opensearch] Allow user-defined labels on pvcs

### ISSUE THREAD

**Issue by simonstumpf** [opensearch-project/helm-charts#554]
**Is your feature request related to a problem? Please describe.**
Our PVCs get backuped based on a policy defined in the PVC label. However it's currently not possible to define additional labels for the PVC (instead the global labels are applied if .Values.persistence.labels.enabled is true). 
**Describe the solution you'd like**
I'd like to define additional labels that are added besides the global labels. 

**Describe alternatives you've considered**
I don't see another way of doing it. 

**Additional context**
-

**Comment by prudhvigodithi** [comment]
[Triage]
I see the PR https://github.com/opensearch-project/helm-charts/pull/555 is already created for this change, thanks for your contribution @simonstumpf.

**Comment by peterzhuamazon** [comment]
Waiting for the backport to 1.x before closing this.

Thanks.

**Comment by simonstumpf** [comment]
@peterzhuamazon 
Thanks!
Should I merge my branch into the 1.x branch or the main?

**Comment by prudhvigodithi** [comment]
Hey @simonstumpf please create a PR to 1.x branch.

**Comment by simonstumpf** [comment]
@prudhvigodithi Im a little bit confused. I've created the PR, but there are too many changes? Do you see what I did wrong?

**Comment by prudhvigodithi** [comment]
@simonstumpf you need to clone 1.x--> add your changes-->then please create the PR to 1.x.

**Comment by peterzhuamazon** [comment]
> @prudhvigodithi Im a little bit confused. I've created the PR, but there are too many changes? Do you see what I did wrong?

Added steps here:
https://github.com/opensearch-project/helm-charts/pull/599#issuecomment-2358934979

**Comment by peterzhuamazon** [comment]
Resolved, closing now.
