### ISSUE TITLE
[BUG][opensearch] Incorrect default listed for opensearchJavaOpts in README.md

### ISSUE THREAD

**Issue by jeidsath** [opensearch-project/helm-charts#566]
README.md documents the default opensearchJavaOpts as "-Xmx1g -Xms1g". The actual default is 512/512. See:

https://github.com/opensearch-project/helm-charts/blob/a018f838ec44dd0b9337e0403a541580cc39c0f3/charts/opensearch/values.yaml#L146

https://github.com/opensearch-project/helm-charts/blob/a018f838ec44dd0b9337e0403a541580cc39c0f3/charts/opensearch/README.md?plain=1#L47

**Comment by dblock** [comment]
@jeidsath care to fix this with a PR? Thanks!

[Catch All Triage - [1](https://github.com/dblock/), [2](https://github.com/krisfreedain), [3](https://github.com/reta)]

**Comment by prudhvigodithi** [comment]
Thanks @jeidsath since the PR was merged, closing this issue, please re-open if required.
Thank you 
@getsaurabh02 @peterzhuamazon
