### ISSUE TITLE
[BUG][opensearch-dashboards, opensearch] Upgrade "opensearch" failed: failed to create resource: ServiceMonitor.monitoring.coreos.com: spec.endpoints[0].port in body must be of type string: "integer"

### ISSUE THREAD

**Issue by kappa8219** [opensearch-project/helm-charts#579]
**Describe the bug**
Upgrade "opensearch" failed: failed to create resource: ServiceMonitor.monitoring.coreos.com "opensearch-cluster-master-service-monitor" is invalid: spec.endpoints[0].port: Invalid value: "integer": spec.endpoints[0].port in body must be of type string: "integer"

**To Reproduce**
1. Upgrade opensearch over helm from 2.22.0 to 2.23.0, dashboards 2.20.0 => 2.21.0 setting value  "serviceMonitor: enabled: true"
2. Helm upgrade failed with error in description

**Expected behavior**
Upgrade successfull

**Chart Name**
Both opensearch-dashboards, opensearch.

**Host/Environment (please complete the following information):**
 - Helm Version: ghcr.io/fluxcd/helm-controller:v1.0.1
 - Kubernetes Version: AWS EKS 1.30

**Comment by eyenx** [comment]
Looks like this issue was introduced with #537 

I'm looking into it and will try to fix it with a PR this afternoon!

**Comment by prudhvigodithi** [comment]
Thanks @eyenx

**Comment by VILJkid** [comment]
Thanks @kappa8219, @eyenx, @prudhvigodithi for pointing this one out!

After going through the [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator/), it was found that the template `port` definition in `ServiceMonitor` template is different from `Service` template.

In short,
- `port` in `ServiceMonitor` means the `name` of the Service port. It's of type `string`.
- `port` in `Service` means the `port` number of the Service. It's of type `int`. 

Thus, the confusion and bug was created in #537

I'll shortly raise a PR with the fix.

**Comment by prudhvigodithi** [comment]
Got it thanks @VILJkid.

**Comment by peterzhuamazon** [comment]
Close this issue as the related PR is merged:
* https://github.com/opensearch-project/helm-charts/pull/581
Thanks.
