### ISSUE TITLE
[BUG][opensearch-dashboard] add protocol TCP for metricsPortName

### ISSUE THREAD

**Issue by dmpe** [opensearch-project/helm-charts#588]
**Describe the bug**

When using server side apply, argocd says

```
Failed to compare desired state to live state: failed to calculate diff: error calculating server side diff: serverSideDiff error: error removing non config mutations for resource Service/opensearch-dashboards: error reverting webhook modified fields in predicted live resource: .spec.ports: element 1: associative list with keys has an element that omits key field "protocol" (and doesn't have default value)
```

Using latest version, helm chart is missing protocol property for metrics port

```
  - name: {{ .Values.service.metricsPortName | default "metrics" }}
    port: {{ .Values.service.metricsPort }}
```

**To Reproduce**

1. Deploy Opensearch dashboard to k8s cluster via ArgoCD
2. observe the error message

**Expected behavior**

Add `protocol: TCP` to the helm chart

**Chart Name**

opensearch-dashboard

**Screenshots**

**Host/Environment (please complete the following information):**
 - Kubernetes Version: v1.28.11+rke2r1
 - argocd: 2.12.1

**Comment by prudhvigodithi** [comment]
This bug is coming from the PR https://github.com/opensearch-project/helm-charts/pull/581, adding @VILJkid and @eyenx to please take a look.
Thank you

**Comment by VILJkid** [comment]
Thanks @dmpe, @prudhvigodithi for pointing this one out!
Looking into this and raising a PR with the fix shortly.
