### ISSUE TITLE
[BUG][opensearch] `helm lint` fails if using `extraObjects`

### ISSUE THREAD

**Issue by cyanidium** [opensearch-project/helm-charts#606]
**Describe the bug**
When running `helm lint` and creating any extra objects using the `extraObjects` value, `helm lint` fails with:

```shell
[ERROR] templates/extraManifests.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: apps/v1
```

**To Reproduce**
1. Create a values.yaml with `extraObjects` defined
2. Run `helm list -f values.yaml charts/opensearch` from the repo top level
3. See error

**Expected behavior**
There should be no errors during linting.

**Chart Name**
opensearch

**Screenshots**

**Host/Environment (please complete the following information):**
 - Helm Version: v3.16.2
 - Kubernetes Version: N/A

**Additional context**
This is a known issue with helm and only affects linting, not the applied templates:
https://github.com/helm/helm/issues/10149

**Comment by prudhvigodithi** [comment]
[Triage]
Thanks @cyanidium we can get the PR's reviewed and merged for this issue.
@peterzhuamazon
