### ISSUE TITLE
[BUG][Opensearch] init container missing pull policy

### ISSUE THREAD

**Issue by anna-intellegens** [opensearch-project/helm-charts#611]
**Describe the bug**
Persistence init container doesn't have a pull policy defined, meaning it defaults to Always, causing it to error on offline deployments

**To Reproduce**
1. Import all required images to a local machine running kubernetes without external network connection
2. Deploy helm chart with persistence enabled and `image.pullPolicy = "Never"` set in values.yaml
3. Opensearch fails to start with ErrImagePull and ImagePullBackOff due to persistence init container

**Expected behavior**
Persistence init container should respect pull policy specified in `image.pullPolicy` similar to other init containers (such as sysctlInit)

**Chart Name**
Opensearch v1.x charts

**Screenshots**

**Host/Environment (please complete the following information):**
 - Helm Version: Tested on both v3.9.1+unreleased (microk8s bundled) and v3.16.2
 - Kubernetes Version: Tested on both Microk8s 1.31, and 1.29.7 via Minikube

**Comment by prudhvigodithi** [comment]
[Triage]
Thanks @anna-intellegens for opening a PR, we can get the PR reviewed and merged.
@peterzhuamazon

**Comment by bshien** [comment]
Since the PR got merged, will go ahead and close the issue. Feel free to reopen if there are any issues.
