### ISSUE TITLE
Support IngressClassName in OpenSearch and OpenSearch Dashboards charts.

### ISSUE THREAD

**Issue by mprimeaux** [opensearch-project/helm-charts#66]
**Is your feature request related to a problem? Please describe.**
Kubernetes 1.18 and greater support the [`IngressClassName`](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation) `spec` stanza as part of the Ingress kind.

**Describe the solution you'd like**
If defined in the chart values file, the Ingress `spec` stanza [should](https://datatracker.ietf.org/doc/html/rfc2119) use the `IngressClassName` value.

**Describe alternatives you've considered**
While we may be able to also leverage an ingress class name annotation, this is not always accepted.

**Additional context**

<details>
<summary>Ingress</summary>
<p>

```diff
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "opensearch.uname" . -}}
{{- $servicePort := .Values.httpPort -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
+  {{- if .Values.ingress.ingressClassName }}
+  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
+  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
  {{- end }}
{{- end }}
```
</p>
</details>

**Comment by peterzhuamazon** [comment]
@mprimeaux could you please change the title to reflect this issue? Thanks.

**Comment by aschi1** [comment]
Hi, is there any update for this? IngressClassName is blocking us to migrate to this helm chart (which we would very much like to)

Thank you!

**Comment by mprimeaux** [comment]
I'll review and update today.

**Comment by mprimeaux** [comment]
@aschi1 PR #149 has been submitted for community review. 

@peterzhuamazon @TheAlgo @DandyDeveloper @smlx FYI and thanks for your continued support.

**Comment by aschi1** [comment]
@mprimeaux Thank you!
