### ISSUE TITLE
Unable to find the field "existingCertSecret" to configure transport-TLS

### ISSUE THREAD

**Issue by divyanshuch1** [opensearch-project/helm-charts#72]
Hello
I am unable to find the field "existingCertSecret" in ````plugins.security.ssl````  in opensearch helm chart to configure transport TLS for nodes.
Earlier , as in **opendistro** , we got it at [here](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/4d440b7473e58651608070f0f5d446c4736e1ccf/helm/opendistro-es/values.yaml#L227)
But not in **opensearch**.
Due to which I am not able to configure TLS using issuer and certificates.
Kindly help.
Thanks

**Comment by TheAlgo** [comment]
@divyanshuch1 I guess you can add it in the [values.yaml](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml#L44). In the current chart the sample value is not given but TLS is configurable.

**Comment by TheAlgo** [comment]
@divyanshuch1 can we close this issue?

**Comment by TheAlgo** [comment]
@divyanshuch1 the PR #80 is merged, let me know if we are good to close this issue. Thanks!

**Comment by divyanshuch1** [comment]
@TheAlgo  Yes sure, we can close this issue.

**Comment by peterzhuamazon** [comment]
Close the issue as @divyanshuch1 requested. Thanks.
