### ISSUE TITLE
Ensure DCO Workflow Check

### ISSUE THREAD

**Issue by peternied** [opensearch-project/helm-charts#76]
Coming from https://github.com/opensearch-project/project-meta/issues/17

A Developer Certificate of Origin is required on commits in the OpenSearch-Project.

See [doc.yml](https://github.com/opensearch-project/.github/blob/main/workflow/dco.yml) for an example workflow.  Ensure CONTRIBUTING.md to has a section on the DCO per the [project template](https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#developer-certificate-of-origin). 

- [x] DCO Check Workflow
- [x] CONTRIBUTING.md DCO Section

**Comment by CEHENKLE** [comment]
This looks resolved to me (contributing points to .github's contributing, which mentions the DCO) and there's a dco.yaml.  Any reason we can't close this out?

Thanks,
/C

**Comment by peternied** [comment]
This was done in https://github.com/opensearch-project/helm-charts/pull/101 Closing out
