### ISSUE TITLE
Add namespace to opensearch resources

### ISSUE THREAD

**Issue by etenzy** [opensearch-project/helm-charts#78]
**Is your feature request related to a problem? Please describe.**
Resources render with namespace "" which results to current namespace of the current context.

**Describe the solution you'd like**
Add namespace to the resources as {{ .Release.Namespace | quote }}

**Comment by TheAlgo** [comment]
@etenzy Which helm version are you using because this feature is available in helm versions greater than 3.2 in according to this [PR](https://github.com/helm/helm/pull/7648). Thanks

**Comment by TheAlgo** [comment]
Closing this issue as well as the PR was closed by the author. Feel free to re-open
