### ISSUE TITLE
[Enhancement][GitHub Actions] Add GitHub Action to auto bump chart version

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/helm-charts#79]
**Is your feature request related to a problem? Please describe.**
[Enhancement][GitHub Actions] Add GitHub Action to auto bump chart version

Right now we require PR creator to bump the chart version when they raise the PR, 
so that the chart releaser can release a new version after merge.

It will be much easier to have a version autobumper, take action after a PR is merged,
and will resolve edge cases where multiple PRs change to the same 1.x.x version and conflict against each other if any of them merge 1st.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**

**Additional context**

**Comment by smlx** [comment]
One way this could work is to start enforcing a standard like https://www.conventionalcommits.org/en/v1.0.0/

**Comment by mprimeaux** [comment]
> One way this could work is to start enforcing a standard like https://www.conventionalcommits.org/en/v1.0.0/

I've been reasoning about this a bit and believe the options partially depend on how the maintainers prefer this repository to operate. 

For example, do you prefer to (1) use `feature`, `defect`, `technical debt`, and `technical risk` branches **only** or (2) also prefer to represent `release` branches? Other? 

Kubernetes employs [long-lived release branches](https://github.com/kubernetes/kubernetes/branches/all) so fixes can easily be made to those versions in support of their deprecation policy. It *appears* OpenSearch is [also going this route](https://github.com/opensearch-project/OpenSearch/branches/all).  

Is the desire to remain with [Github flow](https://guides.github.com/introduction/flow/) or be somewhere between Github flow and [Git flow](https://nvie.com/posts/a-successful-git-branching-model/)?

**Comment by DandyDeveloper** [comment]
@mprimeaux The only thing to remember is you'll have people all over contributing here. 

Definitely defining something already familiar to the OSS (particularly Kubernetes/CNCF) communities would hopefully be easier to take onboard for most. 

I'm not going to weigh in with any additional options as all the above are good. I think owners need to make the call on what gets done. 

+1 in favour of long lived feature branches (Less for the hot fixing, and more for the coherent releases).

**Comment by TheAlgo** [comment]
@mprimeaux @DandyDeveloper 
I am totally with you guys on `long-lived branches`. Initially we started off with `1.0.0` but never followed it after that. In my opinion this will help us draw a line on the number of releases we want to make as well. 

Thinking loud, we can release charts weekly or biweekly and have special slots for any serious bugs or issues. This can streamline the releases and reduce the pain of the contributors as well.

**Comment by smlx** [comment]
> Thinking loud, we can release charts weekly or biweekly and have special slots for any serious bugs or issues. This can streamline the releases and reduce the pain of the contributors as well.

The helm CI tooling is geared for fully automated continuous releases on every MR instead of a manual release process. Is there a problem with automating releases that way?

**Comment by TheAlgo** [comment]
> > Thinking loud, we can release charts weekly or biweekly and have special slots for any serious bugs or issues. This can streamline the releases and reduce the pain of the contributors as well.
> 
> The helm CI tooling is geared for fully automated continuous releases on every MR instead of a manual release process. Is there a problem with automating releases that way?

There is no problem if we can reach on a consensus on how version bump can be automated. I don't mind agile way of releases any day

**Comment by peterzhuamazon** [comment]
As of now there are multiple `1.0.5` version bump PRs in this repo, and we need to constantly ask people to bump their version because another PR has taken over his bumped version number already.

This is a bit worrying to me.
We either disable the version bump requirement or we have an automated way to do this.

Any thoughts?

Thanks.

**Comment by smlx** [comment]
>  We either disable the version bump requirement or we have an automated way to do this.

Another option is to focus on getting PRs reviewed and merged much more rapidly. I'm thinking in the order of days rather than weeks,.

**Comment by TheAlgo** [comment]
Seeing the current scenario I feel we can start off with long lived release branches. If everyone is okay with it I can create one. We can have those branches merged to main after the patch is ready so one and so forth.

**Comment by peterzhuamazon** [comment]
> Seeing the current scenario I feel we can start off with long lived release branches. If everyone is okay with it I can create one. We can have those branches merged to main after the patch is ready so one and so forth.

Do you have a flow in mind of how long lived branches would work?
For example, a simple few lines on how do we backport changes to these long-lived branch and maintain them alongside the main branch.

Thanks.

**Comment by peterzhuamazon** [comment]
We have resolved this by adding community guidelines.
#169
