### ISSUE TITLE
[Enhancement][NA] Contributors need a Slack channel or SNS mechanism to communicate

### ISSUE THREAD

**Issue by DandyDeveloper** [opensearch-project/helm-charts#88]
**Is your feature request related to a problem? Please describe.**
Issues / PRs are getting spammed with so much unnecessary discussion which can be great but makes thing so much slower. 

Can we get an official channel? If not, I'll make an unofficial one somewhere. 

**Describe the solution you'd like**
A Slack channel / Instant message option for communication with the community.

**Comment by DandyDeveloper** [comment]
@TheAlgo @peterzhuamazon @mprimeaux @smlx Since you are all active, super helpful and great at what you do.

Can you give your two cents? I think we need this.

**Comment by DandyDeveloper** [comment]
@TheAlgo Forums don't help us as much for general discussions about issues IMO. 

I just want a way to talk to people quickly about things. Hard to get things done with the current way we do things. 

We can link slack threads if they become relevant to the github issue. I'm open to anything, just want a more relaxed and efficient way to communicate with fellow collaborators.

**Comment by peterzhuamazon** [comment]
@stockholmux ^^
