### ISSUE TITLE
[Enhancement][opensearch / opensearch_dashboard] Option to disable security

### ISSUE THREAD

**Issue by erSitzt** [opensearch-project/helm-charts#89]
Hi

both docker and helm instructions a quite simple to follow, but from what i read and experienced they lead to some situation where nothing works as expected

- ssl as a default causing problems
- login form for dashboard with no easy hint on where to set the username/password

It would be nice to provide a *non-production" values.yaml for both as a quickstart that disable ssl and authentiation.
And at least one example on how to configure the latter...

From futher reading i understand that there is a security plugin in both opensearch and opensearch_dashboard... but for the latter i did not find a way to disable it via config ? only remove the plugin entirely ? which would easily be possible while deploying via helm ?

**Comment by DandyDeveloper** [comment]
@erSitzt We did originally have this but it was overruled in favour of having SSL enabled by default for a reason I don't remember. 

https://opensearch.org/docs/latest/dashboards/install/tls/

This outlines how to disable the different settings available (specifically `server.ssl.enabled` and `opensearch.ssl.verificationMode` should do the trick).

**Comment by DandyDeveloper** [comment]
@erSitzt It's not ideal, I get that. But at least with SSL, even using the demo certificates. You're safer and "closer to production" in terms of functionality.

**Comment by oszymanski** [comment]
> i guess you can just adjust the docker image and override the default container via values.yaml
> 
> image: "opensearchproject/opensearch-dashboards"
> 
> Like here:
> 
> https://opensearch.org/docs/latest/security-plugin/configuration/disable/#remove-opensearch-dashboards-plugin

Well you can successfully override the image used for deployment, but attempting to override imageTag property produces an error:

Error: INSTALLATION FAILED: template: opensearch/templates/statefulset.yaml:9:22: executing "opensearch/templates/statefulset.yaml" at <include "opensearch.majorVersion" .>: error calling include: template: opensearch/templates/_helpers.tpl:93:18: executing "opensearch.majorVersion" at <semver (coalesce .Values.imageTag .Chart.AppVersion "1")>: error calling semver: Invalid Semantic Version

**Comment by peterzhuamazon** [comment]
Security can be disabled right here:
https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/README.md
