### ISSUE TITLE
[Enhancement][opensearch] Make volume permissions init container optional with persistence enabled

### ISSUE THREAD

**Issue by dgonsan** [opensearch-project/helm-charts#91]
**Is your feature request related to a problem? Please describe.**
We were using helm chart version 1.0.0 from the old repository and trying to migrate to the newer versions from this one we found out that a new init container to set the file system permissions was added when persistence is enabled. We are using in some of our k8s instances EFS with dynamic provisioning which doesn't allow to set the permissions on the file system causing the init container to fail and thus the node cannot start.

This wasn't an issue on the previous version without the init container as the EFS CSI driver takes care of setting the permissions so the chown is not needed in that case.

**Describe the solution you'd like**
It should be possible to disable the volume permissions init container when persistence is enabled. Maybe a new property can be added to the values file to enable/disable the init container instead of just checking if persistence is enabled.

**Describe alternatives you've considered**
We are still using version 1.0.0 of the chart as it doesn't have that init container and it works fine for now. Going forward the solution would probably be maintaining a fork of the chart but it would be preferable to have the toggle option in the values file.

**Additional context**
No additional context.

**Comment by DandyDeveloper** [comment]
@peterzhuamazon @dgonsan Added a basic condition to support disabling this.
