### ISSUE TITLE
[Enhancement][OpenSearch/OpenSearch Dashboards] Make 1.1 as default image for opensearch helm charts

### ISSUE THREAD

**Issue by TheAlgo** [opensearch-project/helm-charts#97]
**Is your feature request related to a problem? Please describe.**
Plans for moving the default App Version of charts to use the latest OpenSearch version.

**Describe the solution you'd like**
Change [this](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/Chart.yaml#L24) to `1.1`

**Describe alternatives you've considered**
N/A

**Additional context**
It has been close to 15 days for the launch of OpenSearch 1.1. It will be great to switch the default version of the charts to `1.1`

**Comment by peterzhuamazon** [comment]
Can you please change the title to reflect the content? Thanks.

**Comment by DandyDeveloper** [comment]
@TheAlgo As long as the rollout works with the default values. Definitely go for it.

**Comment by TheAlgo** [comment]
@peterzhuamazon @DandyDeveloper Thanks , I will make a PR for this
